import './globals.css';
import Navbar from '@/components/navbar/Navbar';
import Footer from '@/components/footer/Footer';
import StoreProvider from '@/store/storeProvider';

export const metadata = {
  title: 'kelal Digital',
  description: 'Generated by create next app',
};

export default function RootLayout({ children }) {
  return (
    <html lang='en'>
      <body className='flex flex-col min-h-screen'>
        <StoreProvider>
          <Navbar />
          <main className='flex-grow'>{children}</main>
          <Footer />
        </StoreProvider>
      </body>
    </html>
  );
}
